import turtle
def köşe():
    for i in range(30):
        t.right(3)
        t.forward(3)
t = turtle.Turtle()
t.hideturtle()
t.speed(5)
t.pensize(3)
t.penup()
t.goto(-500,250)
t.pendown()
t.begin_fill()
t.fillcolor("red")
t.forward(1000)
köşe()
t.forward(400)
köşe()
t.forward(1000)
köşe()
t.forward(400)
köşe()
t.end_fill()
t.penup()
t.goto(100,0)
t.pendown()
t.begin_fill()
t.fillcolor("white")
t.goto(-125,100)
t.goto(-125,-100)
t.goto(100,0)
t.end_fill()
turtle.done()